language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

os:
    - linux
    - osx

matrix:
    allow_failures:
        - os: osx

install: true

script:
    - perl computer-stats.pl
    - perl computer-stats.pl -o out_test.csv && rm out_test.csv
